service: lunchbot-app
provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  memorySize: 128
  environment:
    REGION: ${self:provider.region}
    ENVIRONMENT: ${self:provider.stage}

app: lunchbot
tenant: adrianpanicek

plugins:
  - serverless-offline
  - serverless-webpack

#functions:

custom:
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    includeModules: true
    packager: 'npm'

package:
  individually: true