service: alias-app
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  memorySize: 512
  environment:
    TOKEN_SECRET: mysecret # Only for the dev environment
    TOKEN_EXPIRATION: 7d
    TABLE_ALIASES: ${opt:stage, 'dev'}-aliases
    TABLE_USERS: ${opt:stage, 'dev'}-users
    TABLE_REFRESH_TOKENS: ${opt:stage, 'dev'}-refresh-tokens
  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
    Resource:
      - "Fn::GetAtt": [ Aliases, Arn ]
      - "Fn::GetAtt": [ Users, Arn ]
      - "Fn::GetAtt": [ RefreshTokens, Arn ]

app: alias
tenant: adrianpanicek

plugins:
  - serverless-webpack

functions:
  login:
    handler: src/user/login.credentials
    events:
    - http:
        path: login
        method: post
  refresh_token:
    handler: src/user/login.withRefreshToken
    events:
    - http:
        path: refreshToken
        method: post
  register:
    handler: src/user/register.register
    events:
    - http:
        path: register
        method: post

  get_aliases:
    handler: src/alias.get
    events:
      - http:
          path: aliases
          method: get
          request:
            parameters:
              querystrings:
                aliasName: true
  add_access_token:
    handler: src/alias.addAccessToken
    events:
      - http:
          path: /aliases/{id}/accessTokens
          method: POST
          request:
            parameters:
              paths:
                id: true

custom:
  tableLimits:
    dev:
      read: 1
      write: 1

resources:
  # DynamoDB
  - ${file(resources/dynamodb-tables.yml)}