service: alias-app
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  memorySize: 512
  environment:
    ENVIRONMENT: ${self:provider.stage}
    TABLE_PREFIX: ${self:service}-${self:provider.stage}-
    TOKEN_SECRET: mysecret # Only for the dev environment
    TOKEN_EXPIRATION: 7d
    TABLE_ALIASES: ${self:provider.stage}-aliases
    TABLE_USERS: ${self:provider.stage}-users-2
    TABLE_REFRESH_TOKENS: ${self:provider.stage}-refresh-tokens
    TABLE_STASHES: ${self:provider.stage}-stashes
  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
      - dynamodb:CreateTable
    Resource: "arn:aws:dynamodb:*"

app: alias
tenant: adrianpanicek

plugins:
  - serverless-domain-manager
  - serverless-offline
  - serverless-webpack

functions:
  login:
    handler: src/action/user/login.handle
    events:
    - http:
        path: login
        method: post
  refresh_token:
    handler: src/action/user/refresh_token.handle
    events:
    - http:
        path: refreshToken
        method: post
  register:
    handler: src/action/user/register.handle
    events:
    - http:
        path: register
        method: post

  put_stash:
    handler: src/action/stash/put.handle
    events:
    - http:
        path: user/stash
        method: put
        authorizer: authorizer
  get_stash:
    handler: src/action/stash/get.handle
    events:
    - http:
        path: user/stash
        method: get
        authorizer: authorizer

  authorizer:
    handler: src/authorize.handle

  get_alias:
    handler: src/action/alias/get.handle
    events:
      - http:
          path: aliases/{alias}
          method: get
          authorizer: authorizer
          request:
            parameters:
              paths:
                alias: true
  post_alias:
    handler: src/action/alias/post.handle
    events:
    - http:
        path: aliases
        method: post
        authorizer: authorizer

  post_access_token:
    handler: src/action/alias/accessToken/post.handle
    events:
      - http:
          path: /aliases/{alias}/accessTokens
          method: POST
          authorizer: authorizer
          request:
            parameters:
              paths:
                alias: true

custom:
  customDomain:
    domainName: alias.panicek.com
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
  webpackIncludeModules: true

package:
  individually: true