service: lunchbot-app
provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  memorySize: 128
  environment:
    REGION: ${self:provider.region}
    ENVIRONMENT: ${self:provider.stage}
app: lunchbot
org: adrianpanicek

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-cloudside-plugin

functions:
  FetchClockBlock:
    handler: src/function/fetchClockBlock.handler
    event:
      - schedule: cron(0 0 10 ? * MON,TUE,WED,THU,FRI *)
    environment:
      S3BUCKET: !Ref S3BucketImages
  SlackSlashCommand:
    handler: src/function/slackSlashCommand.handler
    environment:
      SLACK_SECRET: ${env:SLACK_SECRET}
    event:
      - http:
          path: slashCommand
          method: get

custom:
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    includeModules: true
    packager: 'npm'

resources:
  Resources:
    S3BucketImages:
      Type: AWS::S3::Bucket

package:
  individually: true