Resources:
  Aliases:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${env:TABLE_ALIASES, self:provider.environment.TABLE_ALIASES}
      AttributeDefinitions:
        - AttributeName: aliasID
          AttributeType: S
      KeySchema:
        - AttributeName: aliasID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableLimits.${opt:stage, self:provider.stage}.read}
        WriteCapacityUnits: ${self:custom.tableLimits.${opt:stage, self:provider.stage}.write}
  Users:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${env:TABLE_USERS, self:provider.environment.TABLE_USERS}
      AttributeDefinitions:
      - AttributeName: userID
        AttributeType: S

      KeySchema:
      - AttributeName: userID
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableLimits.${opt:stage, self:provider.stage}.read}
        WriteCapacityUnits: ${self:custom.tableLimits.${opt:stage, self:provider.stage}.write}
